### ISSUE TITLE
Add date formatter

### ISSUE THREAD

**Issue by andypbarrett** [betolink/earthdata#4]
CMR expects date in iso format.  Need some way to allow dates like YYYY, YYYY-MM, or YYYY-MM-DD.

**Comment by andypbarrett** [comment]
This should do it
```
In [26]: import dateutil.parser as parser

In [27]: import datetime as dt

In [28]: DEFAULT = dt.datetime(1979, 1, 1)

In [29]: parser.parse('2021', default=DEFAULT)
Out[29]: datetime.datetime(2021, 1, 1, 0, 0)

In [30]: parser.parse('2021', default=DEFAULT).isoformat()
Out[30]: '2021-01-01T00:00:00'

In [31]: parser.parse('2021-04', default=DEFAULT).isoformat()
Out[31]: '2021-04-01T00:00:00'

In [32]: parser.parse('2021-04-21', default=DEFAULT).isoformat()
Out[32]: '2021-04-21T00:00:00'

In [33]: parser.parse('2021-04-21 06', default=DEFAULT).isoformat()
Out[33]: '2021-04-21T06:00:00'

```

**Comment by betolink** [comment]
A date parser was added for the latest pre-release version. Should cover these use cases. I'll be working on unit tests to cover this and other query related features. notebook on binder: https://mybinder.org/v2/gh/betolink/earthdata/main

**Comment by betolink** [comment]
Andy, The library now parses the dates using your code! I think I'm going to close this issue.
