### ISSUE TITLE
Connection error to ipinfo.io

### ISSUE THREAD

**Issue by frankinspace** [betolink/earthdata#8]
When I try using the `Auth()` object I get a connection error from ipinfo.io
```
import earthdata

ed_auth = earthdata.Auth()
```
Result:
```
ConnectionError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97ba644fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

My best guess is that JPL IT is blocking connections to `ipinfo.io/ip` from the JupyterLab instance I am trying to run from. I need an alternative way of providing credentials.

**Comment by betolink** [comment]
Thanks for reporting it! I just added code to default to `localhost` if we cannot get our external IP. I'm still working on other bug fixes and adding unittests. The plan is to release another version tonight and this issue should be resolved.

**Comment by betolink** [comment]
the latest pre-release version should fix this as is using bearer tokens not Echo token. Take a look at the [notebook](https://mybinder.org/v2/gh/betolink/earthdata/main)

**Comment by betolink** [comment]
No use of external IPs now, closing this =)
